### PR TITLE
Alpha Release/v1.0.0

### PR DESCRIPTION
**Pull request by HeflerDev**
# Hello Reviewer

It's been some time since I posted the first code review,  so **why do I come with this different repo?** <br>
Well, first of all, I appreciate the first review but **my code was very disorganized**, and its structure was very messy. Also, I was spending more time finding things than actually writing code or thinking. <br>
Having that in mind, I decided to start a new project and a new repo, taking time to study project structure and taking the rails structure as reference for this one, managing the MVC pattern so I could code better.

This project is not my best one, but sure its the most organized, and I appreciate, during the review, any tips and reading material that you may like to recommend me.

Thanks for your attention, have a good review and **happy coding**

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @HeflerDev 
### You have done great so far :clap: However, you have a few issues to fix:-
- [x] We no longer use stickler for linting, rather use github actions, [refer from this link](https://github.com/microverseinc/linters-config/tree/master/javascript) Therefore, delete the stickler file and disable it from the pull request
- [x] Install webpack-dev-server so a user can start the app by running `npm run start`
- [x] Add webpack configuration file and install its dependencies webpack, webpack-cli
- [x] Make the design of the project better, refer to the designs given
organize
- [x] rather do something like this
sample

### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Comment by HeflerDev** [comment]
Had to close and reopen the pull request due to problems with a linter.

Main changes made:

- [x]  Changed from Stickler to github actions
- [x]  Installed webpack dev server to ease the evaluation
- [x]  Added config file 
- [x]  Changed the design and made more clean and simple, also added colors instead of just grayscale.

**Review by Oghenebrume50 — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED

Hi @HeflerDev good job working on this, I see you have made good progress but I would like to point out somethings. Going by the screenshot below I good not run this app, and yes I saw your breakdown on the project readme with the `chmod` command but that just means that weboack was not configured properly. :slightly_smiling_face:  Also Chmod is a Unix command that would not work for a reviewer using windows, please work on webpack configuration and run the project through it without the need to change permission it should work fine  :slightly_smiling_face: 
todo1
todo2

**Please make changes and request for another review** :+1: 
**RAPHAEL NORIODE** :mask: STAY_SAFE

**Comment by HeflerDev** [comment]
Thanks for the feedback, yes I am having a hard time getting used to webpack, but I made some changes and now should be working, also updated the README file with better instructions using NPM.

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @HeflerDev 
### You mad good progress so far, however, you have a few issues to fix:-
- [x] Make the edit functionally easy to recognize and savable
- [x] Solve the errors emitted from the console
console
- [x] The project should be selectable and displays its attached todos
### Make the changes and submit the project for another review. Good luck!
- Happy coding!

By Raymond
Slack @iamraymond

**Comment by HeflerDev** [comment]
Done with requested changes with a few extras:
| - Remove Info from task in Menu
| + Select Task and open menu
| + Menu display information about the task, also can edit and delete task
| / Fix Todo's disappearing on Edit
| + Add More Interaction and Style

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @HeflerDev, great job on this project :+1: However, we still have some improvements we need to make. Kindly check the comments below:
- I could not create a todo. Kindly fix that
- Console errors prevented me from interacting with the app as required. Let us fix that. Kindly check the screenshot below
cnn

Once you are done making the changes, kindly submit another code review :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by HeflerDev** [comment]
Lol I'm so sorry, maybe I did something that broke the app, will fix ASAP

**Review by christianotieno — APPROVED** [review]
# Project Approved 🍾 
Hello guys 👋 
Good job working on the changes. 👏 
All the required changes have been met in this project. I will go ahead and mark them as complete. All the very best in your next tasks 🥇 

### Happy coding 💻

##### Christian Otieno (TSE)

**Pull request merged**
